---
editor: 
  mode: source
---

# Initial Population Abundance {.unnumbered}
                               
There are two ways to set the initial population abundance, defined as the vector of the absolute number of fish alive on January 1^st^ of the first year ($t=1$) of the projection time horizon $\underline{N}(1)$. The primary option is to use a set of samples from the distribution of the estimator of $\underline{N}(1)$. This approach explicitly incorporates uncertainty in the estimate of initial population abundance into the projections. Under this option, either frequentist methods such as bootstrapping or Bayesian methods such as Markov Chain Monte Carlo simulation can be applied to determine the sampling distribution of the estimator of $\underline{N}(1)$. The secondary option is to ignore uncertainty in the estimator of initial population abundance and use a single best estimate for the value of $\underline{N}(1)$. In this case, there is no uncertainty in the point estimate of $\underline{N}(1)$ used in the projections.

The primary option uses a set of $B$ initial population vectors, denoted by $\underline{N}^{(*)}(1) = \left\{ \underline{N}^{(1)}(1), \underline{N}^{(2)}(1), \dots , \underline{N}^{(B)}(1) \right\}$ for stochastic projections. In this case, the set of B values are random samples from the distribution of the estimator of $\underline{N}(1)$  generated by the assessment model or other means. Given this, stochastic projection can be used to characterize the sampling distribution of key fishery outputs accounting for the uncertainty in the estimate of the initial population size. For each initial condition $\underline{N}^{(b)}(1)$, a set of simulations will be performed using the specified harvest strategy. Since dynamic array allocation is used to dimension the set of initial population vectors, the user may choose to input a large number of initial population vectors (e.g., $B=10^3$) within the practical constraint of available computer memory.

The secondary option is to use a single point estimate of  $\underline{N}(1)$for projection. In this case, one estimate of population abundance is assumed to characterize the initial state of the population. Since there is no uncertainty in the initial state of the population this option allows one to characterize the sampling distribution of key fishery outputs due to uncertainty in recruitment or other variables subject to process errors.

Regardless of which initial population abundance option is used, the user must also specify the units of the initial population size vector taken from the assessment model. In particular, the initial population abundance vector is specified and input in relative abundance units along with a conversion coefficient $k_N$ to compute from relative units to absolute numbers, where the initial population abundance replicate is calculated as the conversion coefficient times the relative abundance vector via $\underline{N}^{(b)}(1) = {\Bigl( N_1^{(b)}(1),\  ...,\ N_A^{(b)}(1) \Bigr)} = k_{N} \cdot \underline{n}^{(b)}(1) = {\Bigl(k_N \cdot n_1^{(b)}(1),\ ...,\ k_N \cdot n_A^{(b)}(1) \Bigr)}$
