
## Model 12. Shepherd Curve with Autocorrelated Lognormal Error {.unnumbered}

The Shepherd curve with autocorrelated lognormal error is a parametric model of recruitment generation where survival to recruitment age is density dependent and subject to serially-correlated stochastic variation. *The Shepherd curve with autocorrelated lognormal error model depends on spawning biomass and is time-dependent.*

The Shepherd curve with autocorrelated lognormal error generates recruitment as


$$
\begin{split}
& \hat{r}(t) = \dfrac{\alpha \cdot b_S(t-1)}{ 1 + \left( \dfrac{b_s(t-1)}{k} \right)^{\beta} } \cdot e^{\varepsilon_t} \\
& \\
& where\ \varepsilon_t = \phi\varepsilon_{t-1} + w_t \ \ with\ w_t \sim  N(0,\sigma^2_w), \\ 
& \hat{R}(t) = c_r \cdot \hat{r}(t), and\ B_s(t) = c_B \cdot b_S(t)
\end{split}
\tag{32}\label{eq:32}
$$
The stock-recruitment parameters $\alpha$, $\beta$, $k$, $\phi$, $\varepsilon_0$, and $\sigma^2_w$ and the conversion coefficients for recruitment $c_R$ and spawning stock biomass $c_B$ are specified by the user. The parameter $\varepsilon_0$ is the log-scale residual for the stock-recruitment fit in the time prior to the projection. If this value is not known, the default is to set $\varepsilon_0 = 0$.
