---
editor: 
  mode: source
---

## Model 14. Empirical Cumulative Distribution Function of Recruitment {.unnumbered}

The empirical cumulative distribution function of recruitment can be used to randomly generates recruitment under the assumption that the distribution of $R$ is stationary and independent of stock size. *The empirical cumulative distribution function of recruitment model does not depend on spawning biomass and is time-invariant.*

To describe this nonparametric approach, let $R_S$ denote the $S^{th}$ element in the ordered set of observed recruitment values. The empirical probability density function for $R_S$, denoted as $g(R_s)$, assigns a probability of $1/T$ to each value of $R(t)$ where $T$ is the number of stock-recruitment data points. Let $G(R_S)$ denote the cumulative distribution function (cdf) for $R_S$. Set the values of $G$ at the minimum and maximum observed $R_S$ to be $G(R_{min})=0$ and $G(R_{max})=0$ so that the cdf of $R_S$ can be written as

$$
G(R_S) = \frac{s-1}{T-1} \tag{34}\label{eq:34}
$$

Random values of $R_S$ can be generated by applying the probability integral transform to the empirical cdf. To do this, let $U$ be a uniformly distributed random variable on the interval [0,1]. The value of $R_S$ corresponding to a randomly chosen value of $U$ is determined by applying the inverse function of the cdf $G(R_S)$. In particular, if $U$ is an integer multiple of $1/(T-1)$ so that $U = s/(T-1)$ then $\widehat{R_s} = G^{-1}(U)$. Otherwise $\widehat{R_s}$ can be obtained by linear interpolation when $U$ is not a multiple of $1/(T-1)$.

In particular, if $(s-1) / (T-1) < U < s/ (T-1)$, then $\widehat{R_s}$ is interpolated between $R_S$ and $R_{S+1}$ as

$$
U = \left(\frac{\dfrac{s}{T-1}-\dfrac{s-1}{T-1}}{R_{S+1} - R_S} \right)\left(\widehat{R_S}-R_S\right) + \frac{s-1}{T-1}
\tag{35}\label{eq:35}
$$

Solving for $\widehat{R_s}$ as a function of $U$ yields

$$
\widehat{R_S} = (T-1)(R_{S+1}-R_S)\left(U-\frac{s-1}{T-1}\right)+R_S \tag{36}\label{eq:36}
$$

where the interpolation index $s$ is determined as the greatest integer in $1+U(T-1)$. Given the value of $R_S$, recruitment is set to be

$$
\widehat{R}(t) = \widehat{R_S} \tag{37}\label{eq:37}
$$
The AGEPRO program can generate stochastic recruitments under model 14 based on thousands of input recruitment data points.
