---
editor: 
  mode: source
---

## Model 2. Empirical Recruits Per Spawning Biomass Distribution {.unnumbered}

For some stocks, the distribution of recruits per spawner may be independent of the number of spawners over the range of observed data. The recruitment per spawning biomass $(R/B_s)$ model randomly generates recruitment under the assumption that the distribution of the $R/B_s$ ratio is stationary and independent of stock size. *The empirical recruits per spawning biomass distribution model depends on spawning biomass and is time-invariant.*

To describe this nonparametric approach, let $S_t$ be the $R/B_s$ ratio for the t^th^ stock recruitment data point assuming age-1 recruitment

$$
S-t = \frac{R(t)}{B_s(t-1)} \tag{17}\label{eq:17}
$$

and let $R_S$ be the thS element in the ordered set of $S_t$. The empirical probability density function for $R_S$, denoted as $g(R_S)$, assigns a probability of $1/T$ to each value of $R/B_S$ where $T$ is the number of stock-recruitment data points. Let $G(R_S)$ denote the cumulative distribution function (cdf) for $R_S$. Set the values of $G$ at the minimum and maximum observed $R_S$ to be $G(R_{min}) = 0$ and $G(R_{max}) = 0$ so that the cdf of $R_S$ can be written as

$$
G(R_S) = \frac{s-1}{T-1} \tag{18}\label{eq:18}
$$

Random values of $R_S$ can be generated by applying the probability integral transform to the empirical cdf. To do this, let $U$ be a uniformly distributed random variable on the interval \[0,1\]. The value of $R_S$ corresponding to a randomly chosen value of $U$ is determined by applying the inverse function of the cdf $G(R_S)$. In particular, if $U$ is an integer multiple of $1/(T-1)$ so that $U=s/(T-1)$ then $R_S = G^{-1}(U)$. Otherwise $R_S$ can be obtained by linear interpolation when $U$ is not a multiple of $1/(T-1)$.

In particular, if $(s-1)/(T-1)<U<s/(T-1)$, then $\hat{R_S}$ is interpolated between $R_S$ and $R_{S+1}$ as

$$
U = \left(\frac{\dfrac{s}{T-1} - \dfrac{s-1}{T-1}}{R_{s+1}-R_S} \right) (\widehat{R_S} - R_S) + \frac{s-1}{T-1} \tag{19}\label{eq:19}
$$

Solving for $\widehat{R_S}$ as a function of $U$ yields

$$
\widehat{R_S} - (T - 1)(R_{S+1} - R_S)\left(U - \frac{s-1}{T-1}\right) + R_{S}\ \tag{20}\label{eq:20}
$$

Where the interpolation index s is determined as the greatest integer in $1+U(T-1)$. Given the value of $\widehat{R_S}$, recruitment is generated as

$$
R(t) = N_1(t) = B_S(t-1) \cdot \widehat{R_S} \tag{21}\label{eq:21}
$$

The AGEPRO program can generate stochastic recruitments under model 2 based on thousands of input stock-recruitment data points (i.e., the stock-recruitment data array size is defined as a long int variable in the C language and is user specified with the input variable MaxRecObs, see Table 3, keyword RECRUIT) conditioned on available computer memory resources.
