---
editor: 
  mode: source
---

## Model 4. Two-Stage Empricial Recruits Per Spwaning Biomass {.unnumbered}

The two-stage recruits per spawning biomass model is a direct generalization of the $R/B_S$ model where the spawning stock of the population is categorized into “low” and “high” states. *The two-stage empirical recruits per spawning biomass distribution model depends on spawning biomass and is time-invariant.*

In this model, there is an $R/B_S$ distribution for the low spawning biomass state and an $R/B_S$ distribution for the high spawning biomass state. Let $G_{Low}$ be the cdf and let $T_Low$ be the number of $R/B_S$ values for the low $B_S$ state. Similarly, let $G_{High}$ be the cdf and let $T_{High}$ be the number of $R/B_S$ values for the high $B_S$ state. Further, let $B^*_S$ B denote the cutoff level of $B_S$ such that, if $B_S > B^*_S$, then $B_S$ falls in the high state. Conversely if $B_S <B^*_S$, then $B_S$ falls in the low state. Recruitment is stochastically generated from $G_{Low}$ or $G_{High}$ using equations (\ref{eq:20}) and (\ref{eq:21}) dependent on the $B_S$ state. The AGEPRO program can generate stochastic recruitments under model 4 based on thousands of input stock recruitment data points per $B_S$ state.
