## Model 1. Markov Matrix {.unnumbered}

A Markov matrix approach to modeling recruitment may be useful when there is uncertainty about the functional form of the stock-recruitment relationship. A Markov matrix contains transition probabilities that define the probability of obtaining a given level of recruitment given that $B_S$ was within a defined interval range. In particular, the distribution of recruitment is assumed to follow a multinomial distribution conditioned on the spawning biomass interval or spawning state of the stock. The Markov matrix model depends on spawning biomass and is time-invariant.

An empirical approach to estimate a Markov matrix uses stock-recruitment data to determine the parameters of a multinomial distribution for each spawning biomass state. In this case, matrix elements can be empirically determined by counting the number of times that a recruitment observation interval lies within a given spawning biomass state, defined by an interval of spawning biomass, and normalizing over all spawning states. To do this, assume that there are $K$ recruitment values and $J$ spawning biomass states. The spawning biomass states are defined by disjoint intervals on the spawning biomass axis

$$
I_1 = {\bigl[0,B_{s,1}\bigr)}\ and\ for\ j=1, ..., J-2\ \ I_j = {\bigl[B_{S,j-1},B_{S,J}\bigr)}\ and\ I_j = {\bigl[B_{S,J-1}, \infty\bigr)}    
\tag{14}\label{eq:14}
$$

where the spawning biomass values $B_{S,j}$ are the input endpoints of the disjoint intervals of categories of spawning biomass (e.g., high, medium, low). Note that the spawning biomass intervals are defined by the cut points $B_{S,j}$. The conditional probability of realizing the $k^{th}$ recruitment value given that observed spawning biomass $B_{S,Observed}$ is in the $j^{th}$ interval is $P{j,k}$. Here $P_{j,k}$ is the element in the $j^{th}$ row and $k^{th}$ column of the Markov matrix $\underline{P}={\bigl[ P_{j,k}\bigr]}$ of conditional recruitment probabilities with elements

$$
P_{j,k} = Pr{\bigl(R_k | B_{S,Observed} \in I_j\bigr)} \tag{15}\label{eq:15}
$$ These individual conditional probabilities can be estimated by the computing the number of points in the stock recruitment data set that fall within a selected recruitment $[O_{k-1},O_k]$ range conditioned on the spawning biomass interval $I_j$. If $x_{j,k}$ represents the number of stock-recruitment observations in cell $I_j \times O_k$ and there is at least one observation in spawning state $j$, then the empirical maximum likelihood estimate of $P_{j,k}$ is

$$
Pr(r=O_k\ |\ B_S \in I_j)= \frac{x_{j,k}}{ \sum_\limits{k}x_{j,k} } \tag{16}\label{eq:16}
$$ Here $P_{j,k} \ge 0$ and $\sum\limits_{k=1}P_{j,k}=1$

Up to 25 recruitment values and up to 10 spawning biomass states can be used in the Markov matrix model. For each spawning biomass interval, the user needs to specify the conditional probabilities of realizing the expected recruitment level, e.g., the $P_{j,k}$. Given the conditional probabilities $P_{j,k}$, simulated values of $\hat{R}$ are generated by randomly sampling the conditional distribution $\hat{R}(t) = Pr(R=O_k\ |\ B_S(t) \in I_j)$ through time.
