---
editor: 
  mode: source
---

## Model 15. Two Stage Empirical Cumulative Distribution Function of Recruitment {.unnumbered}

The two-stage empirical cumulative distribution function of recruitment model is an extension of [Model 14](#model-14.-empirical-cumulative-distribution-function-of-recruitment) where the spawning stock of the population is categorized into low and high states. *The two-stage empirical cumulative distribution function of recruitment model depends on spawning biomass and is time-invariant.*

In this model, there is an empirical recruitment distribution $R_{Low}$ for the low spawning biomass state and an empirical recruitment distribution $R_{High}$ for the high spawning biomass state. Let $G_{Low}$ be the cdf and let $T_{Low}$ be the number of $R$ values for the low $B_S$ state. Similarly, let $G_{High}$ be the cdf and let $T_{High}$ be the number of $R$ values for the high $B_S$ state. Further, let $B_S^*$ denote the cutoff level of $B_S$ such that, if $B_S > B_S^*$, then $B_S$ falls in the high state. Conversely if $B_S < B_S^*$, then $B_S$ falls in the low state. Recruitment is stochastically generated from $G_{Low}$ or $G_{High}$ using equations (\ref{eq:36}) and (\ref{eq:37}) dependent on the $B_S$ state. The AGEPRO program can generate stochastic recruitments under model 15 based on thousands of input stock-recruitment data points per $B_S$ state.
