---
editor: 
  mode: source
---

## Biomass Thresholds {.unnumbered}

The user can specify biomass thresholds for spawning biomass $\bigl(B_{S,THRESHOLD}\bigr)$, mean biomass $\bigl(\overline{B}_{THRESHOLD}\bigr)$, and total stock biomass $\bigl(B_{T,THRESHOLD}\bigr)$ for Sustainable Fisheries Act (SFA) policy evaluation. These biomass thresholds can be specified using the input keyword REFPOINT (Tables 2 and 3). If the REFPOINT keyword is used in an AGEPRO model, then projected biomass values are compared to the input thresholds through time. Probabilities that biomasses meet or exceed threshold values are computed for each year. In addition, the probability that biomass thresholds were exceeded in at least one year within a single simulated population trajectory is computed. If the user specifies fishing mortality-based harvesting with no landings quotas, then the SFA-threshold probabilities are computed over the entire set of simulations. Let $K_B(t)$ be the number of times that projected biomass $B(t)$ meets or exceeds a threshold biomass $B_{THRESHOLD}$ in year $t$. The counter $K_B(t)$ is evaluated for each year and biomass series (spawning, mean, or total stock). Given that $K_{TOTAL}$ is the total number of feasible simulation runs, the estimate of the annual probability that $B_{THRESHOLD}$ would be met or exceeded in year $t$ is

$$
\Pr(B(t)) \ge B_{THRESHOLD} = \frac{K_B(t)}{K_{TOTAL}} \tag{50}\label{eq:50}
$$

Note that this also provides an estimate of the probability of the complementary event that biomass does not exceed the threshold via

$$
\Pr(B(t) < B_{THRESHOLD}) = 1 - \Pr(B(t) \ge B_{THRESHOLD} ) = 1 - \frac{K_B(t)}{K_{TOTAL}} \tag{51}\label{eq:51}
$$

Next, if $K_{THRESHOLD}$ denotes the number of simulations where biomass exceeded its threshold at least once, then the probability that $K_{THRESHOLD}$ would be met or exceeded at least

$$
\Pr(\exists{t} \in [1,2,\dots,Y]\ such\ that\ B(t) \ge B_{THRESHOLD}) = \frac{K_{THRESHOLD}}{K_{TOTAL}} \tag{52}\label{eq:52}
$$

If the user specifies landings quota-based harvesting in one or more years, then the SFA-threshold probabilities can be computed over the set of feasible simulations. In this case, the year-specific conditional probability that $B_{THRESHOLD}$ would be met or exceeded for feasible simulations is

$$
\Pr(B(t)) \ge B_{THRESHOLD} = \frac{K_B(t)}{K_{FEASIBLE}} \tag{53}\label{eq:53}
$$

Note that the counter $K_B(t)$ can only be incremented in a feasible simulation. In contrast, the joint probability that $B_{THRESHOLD}$ would be met or exceeded for the entire set of simulations is given by (\ref{eq:52}) and the probability that $B_{THRESHOLD}$ would be met or exceeded at least once during the projection time horizon is given by (\ref{eq:53}).
