---
editor: 
  mode: source
---

# Abstract {.unnumbered}

This reference manual describes the updated version 4.25 AGEPRO model and software to perform stochastic age-structured projections for an exploited age-structured fish stock. The AGEPRO model can be used to quantify the probable effects of alternative harvest scenarios by multiple fleets on an age-structured population over a given time horizon. Primary outputs include the projected distribution of spawning biomass, fishing mortality, recruitment, and landings by time period. This updated version allows for multiple recruitment models to account for alternative hypotheses about recruitment dynamics and applies model-averaging to predict the distribution of realized recruitment given estimates of recruitment model probabilities. The reference manual also describes the logical structure of the projection model, including program inputs, outputs, structure and usage. This includes three examples which illustrate: a standard two-fleet projection analysis projection, a stock rebuilding projection analysis, and projections to calculate the annual catch limits that produce probabilities of exceeding an overfishing level. Although all reasonable efforts have been taken to ensure the accuracy and reliability of the AGEPRO software and data, the National Oceanic and Atmospheric Administration and the U.S. Government do not and cannot warrant the performance or results that may be obtained by using this software or data.
