# Introduction

The AGEPRO model was initially developed in 1994 to determine optimal strategies to rebuild a depleted fish stock. The model was reviewed at the May 1994 meeting of the Northeast Fisheries Science Center Methods Working Group [@BrodziakRago1994 ; @BrodziakEtAl1998]. Subsequently, the model was applied to groundfish stocks at the 18th SARC [@NEFSC1994] to evaluate Amendment 5 harvest scenarios [@NEFMC1994] and was applied again in 1995 to assist with Amendment 7 [@NEFMC1996]. The reference manual was prepared in 1997 to provide documentation and has been updated since then to describe modifications to the model and software. The current program is written in the C language to allow for dynamic array allocation and to achieve rapid processing speeds.

The AGEPRO program can be used to perform stochastic projections of the abundance of an exploited age-structured population over a given time horizon. The primary purpose of the AGEPRO model is to produce management strategy projections that characterize the sampling distribution of key fishery system outputs such as landings, spawning stock biomass, population age structure, and fishing mortality from one or more fleets, accounting for uncertainty in initial population estimates, future recruitment, and natural mortality (Figure 1). The acronym “AGEPRO” derives from **age**-structured **pro**jections, in contrast to size- or biomass-based projections for size- or biomass-structured models. The user can evaluate alternative harvest scenarios by setting quotas or fishing mortality rates in each year of the time horizon.

Three elements of uncertainty can be included in an AGEPRO stock projection: **population recruitment**, **distribution of initial population size**, and **process error for population and fishery processes**. Recruitment is the primary stochastic element in the population model, where recruitment is typically defined as the number of age-0 or age-1 fish entering the modeled population at the beginning of each year in the time horizon. There are a total of fifteen stochastic recruitment models that can be used for population projection. It is also possible to simulate a deterministic recruitment trajectory (see recruitment model 3 below).

Initial population size is the second potential element of uncertainty for population projection (Figure 1). To include this element, a distribution of initial population sizes must be calculated a priori. This is typically done using bootstrapping, Markov chain Monte Carlo simulation, or other techniques in most age-structured assessments. Alternatively, projections can be based on a single best point estimate with no uncertainty in the initial population size.

The third element of uncertainty is process error in population and fishery processes. The user can choose to simulate the following population and fishery processes at age through time with a multiplicative lognormal process error with mean value equal to unity and a constant coefficient of variation:

  1. Natural mortality at age
  2. Maturation fraction at age
  3. Stock weight on January 1^st^ at age
  4. Spawning stock weight at age
  5. Mean population weight at age
  6. Fishery selectivity at age
  7. Discard fraction at age
  8. Catch weight at age
  9. Discard weight at age
  
The simulated values of each of these processes can be stored in auxiliary data files for the purpose of documenting projection results.
