---
editor: 
  mode: source
crossref: 
  tbl-labels: alpha 1
---

## Table 1: Glossary of AGEPRO variables {.unnumbered}

+---------------------+-------------------------------------------------------------------------------------------------+
| Variable            | Description                                                                                     |
+=====================+=================================================================================================+
| $A$                 | Age of plus-group (fish age-$A$ and older) and last index value for $\underline{N}$             |
+---------------------+-------------------------------------------------------------------------------------------------+
| $B_S(t)$            | Spawning biomass in year $t$                                                                    |
+---------------------+-------------------------------------------------------------------------------------------------+
| $\overline{B}(t)$   | Mean stock biomass in year $t$                                                                  |
+---------------------+-------------------------------------------------------------------------------------------------+
| $B_T$               | Total stock biomass on January $1^{st}$ of year $t$                                             |
+---------------------+-------------------------------------------------------------------------------------------------+
| $B$                 | Number of input initial population vectors $\underline{N}(t)$                                   |
+---------------------+-------------------------------------------------------------------------------------------------+
| $C_a(t)$            | Total catch number of age-$a$ fish that are caught in year $t$                                  |
+---------------------+-------------------------------------------------------------------------------------------------+
| $C_{a,v}(t)$        | Number of age-$a$ fish caught by fleet $v$ in year $t$                                          |
+---------------------+-------------------------------------------------------------------------------------------------+
| $D(t)$              | Total weight of fish discarded fish in year $t$                                                 |
+---------------------+-------------------------------------------------------------------------------------------------+
| $F(t)$              | Instantaneous fully-selected fishing mortality rate in year $t$                                 |
+---------------------+-------------------------------------------------------------------------------------------------+
| $F_a(t)$            | Total fishing mortality rate for age-$a$ fish in year $t$                                       |
+---------------------+-------------------------------------------------------------------------------------------------+
| $F_{a,v}(t)$        | Fishing mortality rate on age-$a$ fish by fleet $v$ in year $t$                                 |
+---------------------+-------------------------------------------------------------------------------------------------+
| $F_B$               | Instantaneous fishing mortality weighted by mean biomass in year $t$                            |
+---------------------+-------------------------------------------------------------------------------------------------+
| $H(t)$              | Harvest index for year $t$.                                                                     |
|                     |                                                                                                 |
|                     | - If $H(t)=1$, then harvest is based on a specified landings quota $Q(t)$ in metric tons        |
|                     |                                                                                                 |  
|                     | - Else if $H(t) = 0$,                                                                           | 
|                     |   then harvest is based on a fishing mortality rate $F(t)$                                      |
+---------------------+-------------------------------------------------------------------------------------------------+
| $L_v(t)$            | Total weight of fish landed by fleet $v$ in year $t$                                            |
+---------------------+-------------------------------------------------------------------------------------------------+
| $M_a(t)$            | Instantaneous natural mortality rate of age-$a$ fish in year $t$                                |
+---------------------+-------------------------------------------------------------------------------------------------+
| $N_a(t)$            | Number of age-$a$ fish alive on January 1st of year $t$                                         |
+---------------------+-------------------------------------------------------------------------------------------------+
| $N_M$               | Number of recruitment models used in the projection                                             |
+---------------------+-------------------------------------------------------------------------------------------------+
| $d_{a,v}(t)$        | Proportion of age-$a$ fish caught by fleet $v$ and discarded in year $t$                        |
+---------------------+-------------------------------------------------------------------------------------------------+
| $S_{a,v}(t)$        | Fishery selectivity for age-$a$ fish by fleet $v$ in year $t$                                   |
+---------------------+-------------------------------------------------------------------------------------------------+
| $P_{R,i}(t)$        | Probability that the $i^{th}$ recruitment model is applied in year $t$                          |
+---------------------+-------------------------------------------------------------------------------------------------+
| $p_{a}(t)$          | Fraction of of age-$a$ fish that are sexually mature in year $t$                                |
+---------------------+-------------------------------------------------------------------------------------------------+
| $\varphi(t)$        | Fraction of total mortality occurring prior to spawning in year $t$                             |
+---------------------+-------------------------------------------------------------------------------------------------+
| $Q_v(t)$            | Landings quota (mt) for fleet $v$ in year $t$                                                   |
+---------------------+-------------------------------------------------------------------------------------------------+
| $R(t)$              | Recruitment (number of age-1 fish on January $1^{st}$) in year $t$                              |
+---------------------+-------------------------------------------------------------------------------------------------+
| $W_{P,a}(t)$        | Average _population weight_ of an age-$a$ fish on January $1^{st}$ in year $t$                  |
+---------------------+-------------------------------------------------------------------------------------------------+
| $W_{L,a,v}(t)$      | Average _landed (catch) weight_ of age of an age-$a$ fish by fleet $v$ in year $t$              |
+---------------------+-------------------------------------------------------------------------------------------------+
| $W_{S,a}(t)$        | Average _spawning weight_ of an age-$a$ fish in year $t$                                        |
+---------------------+-------------------------------------------------------------------------------------------------+
| $W_{MY,a}(t)$       | Average mid-year, or _mean population weight_ of an age-$a$ fish in year $t$                    |
+---------------------+-------------------------------------------------------------------------------------------------+
| $W_{D,a,v}(t)$      | Average _discarded weight_ of an age-$a$ fish by fleet-$v$ in year $t$                          |
+---------------------+-------------------------------------------------------------------------------------------------+
| $Y$                 | Number of Years in projection time horizon where $t= 1,2,...,Y$                                 |
+---------------------+-------------------------------------------------------------------------------------------------+

: Glossary of variables in the AGEPRO module. {#tbl-1}
