---
editor: 
  mode: source
crossref: 
  tbl-labels: alpha 2
---

## Table 2: AGEPRO Keyword Parameters {.unnumbered}

+--------------------+------------------------------------------------------------------------------------------------+
| Keyword            | Purpose                                                                                        |
+====================+================================================================================================+
| `GENERAL`          | Input general model parameters                                                                 |
+--------------------+------------------------------------------------------------------------------------------------+
| `CASEID`           | Input title identifying model attributes                                                       |
+--------------------+------------------------------------------------------------------------------------------------+
| `BOOTSTRAP`        | Input information for bootstrap numbers at age file                                            |
+--------------------+------------------------------------------------------------------------------------------------+
| `HARVEST`          | Input information for harvest intensity ($F$ or $Q$) by fleet                                  |
+--------------------+------------------------------------------------------------------------------------------------+
| `RETROADJUST`      | Input information for retrospective bias adjustment                                            |
+--------------------+------------------------------------------------------------------------------------------------+
| `NATMORT`          | Input information for natural mortality rate ($M$) at age                                      |
+--------------------+------------------------------------------------------------------------------------------------+
| `BIOLOGICAL`       | Input information on seasonal spawning timing for $F$ and $M$                                  |
+--------------------+------------------------------------------------------------------------------------------------+
| `MATURITY`         | Input information on maturity at age                                                           | 
+--------------------+------------------------------------------------------------------------------------------------+
| `STOCK_WEIGHT`     | Input information on stock weights (Jan $1^{st}$) at age                                       |
+--------------------+------------------------------------------------------------------------------------------------+
| `SSB_WEIGHT`       | Input information on spawning biomass weights at age                                           |
+--------------------+------------------------------------------------------------------------------------------------+
| `MEAN_WEIGHT`      | Input information on mean weights at age                                                       |
+--------------------+------------------------------------------------------------------------------------------------+
| `FISHERY`          | Input information on fishery selectivity at age by fleet                                       |
+--------------------+------------------------------------------------------------------------------------------------+
| `DISCARD`          | Input information on discard fraction of numbers at age                                        |
+--------------------+------------------------------------------------------------------------------------------------+
| `CATCH_WEIGHT`     | Input information on catch weights at age                                                      |
+--------------------+------------------------------------------------------------------------------------------------+
| `DISC_WEIGHT`      | Input information on discard weights at age                                                    |
+--------------------+------------------------------------------------------------------------------------------------+
| `RECRUIT`          | Input information on recruitment model                                                         |
+--------------------+------------------------------------------------------------------------------------------------+
| `BOUNDS`           | Input bounds on simulated fish weights and natural mortality rates                             |
+--------------------+------------------------------------------------------------------------------------------------+
| `OPTIONS`          | Input information on projection output                                                         |
+--------------------+------------------------------------------------------------------------------------------------+
| `SCALE`            | Input information on scaling factors for biomass, recruitment, and stock size                  |
+--------------------+------------------------------------------------------------------------------------------------+
| `PERC`             | Input information for setting a specific percentile for the distributions of outputs           |
+--------------------+------------------------------------------------------------------------------------------------+
| `REFPOINT`         | Input information for reference points                                                         |
+--------------------+------------------------------------------------------------------------------------------------+
| `REBUILD`          | Input information for calculating $F$ to rebuild spawning biomass                              |
+--------------------+------------------------------------------------------------------------------------------------+
| `PSTAR`            | Input information for calculating $TAC$ to produce $P*$ which is the probability of            |
|                    | overfishing in the target projection year.                                                     |
+--------------------+------------------------------------------------------------------------------------------------+

: Table of AGEPRO input file keywords. {#tbl-2}

